#action tests
on:
  push:
    branches: [master]
jobs:
  vm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: uname -a && java -version && mvn -version
        
        
